In [1]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import ipywidgets as widgets
from IPython.display import display

## DateTime

In [21]:
#Date Time
df = pd.read_csv(f'Youtube\Egor Books\Youtube-main\Youtube-main\Time-Series-Crash-Course\AirPassengers.csv', index_col=[0], parse_dates = True)
df.index = pd.to_datetime(df.index, format='%Y-%m')
df['Month Name'] = pd.DatetimeIndex(df.index)
df['Month Name'] = df['Month Name'].dt.strftime('%b')
df.head()

            #Passengers Month Name
Month
1949-01-01          112        Jan
1949-02-01          118        Feb
1949-03-01          132        Mar
1949-04-01          129        Apr
1949-05-01          121        May

$$ Data \; Aggregration \; Functions $$

In [27]:
world_happiness_df = pd.read_csv(f'Datasets/World_Happiness_2015.csv')
world_happiness_df.head()

,Country,Region,Happiness Rank,Happiness Score,Standard Error,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
0,Switzerland,Western Europe,1,7.587,0.03411,1.39651,1.34951,0.94143,0.66557,0.41978,0.29678,2.51738
1,Iceland,Western Europe,2,7.561,0.04884,1.30232,1.40223,0.94784,0.62877,0.14145,0.43630,2.70201
2,Denmark,Western Europe,3,7.527,0.03328,1.32548,1.36058,0.87464,0.64938,0.48357,0.34139,2.49204
3,Norway,Western Europe,4,7.522,0.03880,1.45900,1.33095,0.88521,0.66973,0.36503,0.34699,2.46531
4,Canada,North America,5,7.427,0.03553,1.32629,1.32261,0.90563,0.63297,0.32957,0.45811,2.45176

In [38]:
#Create GroupBy of column in dataframe we want to use to group the data
Region_Grouping = world_happiness_df.groupby('Region')
world_happiness_df['Region'].value_counts().head()

Region
Sub-Saharan Africa                 40
Central and Eastern Europe         29
Latin America and Caribbean        22
Western Europe                     21
Middle East and Northern Africa    20
Name: count, dtype: int64

In [41]:
#Use Get Group : Here all rows with region of Sub-Saharan Africa is selected
#                Returns a dataframe object
Region_Grouping.get_group('Sub-Saharan Africa').head()

#Attribute .groups() returns dictionary of indexs corresponding to each group
Region_Grouping.groups

{'Australia and New Zealand': [8, 9], 'Central and Eastern Europe': [30, 43, 44, 51, 53, 54, 55, 58, 59, 61, 63, 68, 69, 72, 76, 79, 82, 85, 86, 88, 92, 94, 95, 103, 105, 110, 126, 129, 133], 'Eastern Asia': [37, 45, 46, 71, 83, 99], 'Latin America and Caribbean': [11, 13, 15, 22, 24, 26, 29, 31, 32, 39, 40, 41, 42, 47, 50, 52, 56, 57, 64, 97, 104, 118], 'Middle East and Northern Africa': [10, 19, 21, 27, 34, 38, 48, 62, 67, 75, 81, 91, 102, 106, 107, 109, 111, 134, 135, 155], 'North America': [4, 14], 'Southeastern Asia': [23, 33, 60, 73, 74, 89, 98, 128, 144], 'Southern Asia': [78, 80, 108, 116, 120, 131, 152], 'Sub-Saharan Africa': [70, 77, 84, 90, 93, 96, 100, 112, 113, 114, 115, 117, 119, 121, 122, 123, 124, 125, 127, 130, 132, 136, 137, 138, 139, 140, 141, 142, 143, 145, 146, 147, 148, 149, 150, 151, 153, 154, 156, 157], 'Western Europe': [0, 1, 2, 3, 5, 6, 7, 12, 16, 17, 18, 20, 25, 28, 35, 36, 49, 65, 66, 87, 101]}

In [ ]:
''' 
Calculate aggegrations of each group : returns series

       Sum(), Mean(), count(), min(), max() exist as well


'''

print(Region_Grouping.size())

#Specify numeric_only=True to ensure only numeric columns are considered 
print('\n', Region_Grouping.mean(numeric_only=True))

Region
Australia and New Zealand           2
Central and Eastern Europe         29
Eastern Asia                        6
Latin America and Caribbean        22
Middle East and Northern Africa    20
North America                       2
Southeastern Asia                   9
Southern Asia                       7
Sub-Saharan Africa                 40
Western Europe                     21
dtype: int64

                                  Happiness Rank  Happiness Score  \
Region
Australia and New Zealand              9.500000         7.285000
Central and Eastern Europe            79.000000         5.332931
Eastern Asia                          64.500000         5.626167
Latin America and Caribbean           46.909091         6.144682
Middle East and Northern Africa       77.600000         5.406900
North America                         10.000000         7.273000
Southeastern Asia                     81.222222         5.317444
Southern Asia                        113.142857         4.580857
Sub-Saharan Africa                   127.900000         4.202800
Western Europe                        29.523810         6.689619

                                 Standard Error  Economy (GDP per Capita)  \
Region
Australia and New Zealand              0.037270                  1.291880
Central and Eastern Europe             0.045208                  0.942438
Eastern Asia                           0.037225                  1.151780
Latin America and Caribbean            0.061127                  0.876815
Middle East and Northern Africa        0.046337                  1.066974
North America                          0.036960                  1.360400
Southeastern Asia                      0.042691                  0.789054
Southern Asia                          0.032161                  0.560486
Sub-Saharan Africa                     0.055299                  0.380473
Western Europe                         0.037625                  1.298596

                                   Family  Health (Life Expectancy)   Freedom  \
Region
Australia and New Zealand        1.314450                  0.919965  0.645310
Central and Eastern Europe       1.053042                  0.718774  0.358269
Eastern Asia                     1.099427                  0.877388  0.462490
Latin America and Caribbean      1.104720                  0.703870  0.501740
Middle East and Northern Africa  0.920490                  0.705615  0.361751
North America                    1.284860                  0.883710  0.589505
Southeastern Asia                0.940468                  0.677357  0.557104
Southern Asia                    0.645321                  0.540830  0.373337
Sub-Saharan Africa               0.809085                  0.282332  0.365944
Western Europe                   1.247302                  0.909148  0.549926

                                 Trust (Government Corruption)  Generosity  \
Region
Australia and New Zealand                             0.392795    0.455315
Central and Eastern Europe                            0.086674    0.152264
Eastern Asia                                          0.127695    0.225885
Latin America and Caribbean                           0.117172    0.217788
Middle East and Northern Africa                       0.181702    0.190376
North America                                         0.244235    0.429580
Southeastern Asia                                     0.151276    0.419261
Southern Asia                                         0.102536    0.341429
Sub-Saharan Africa                                    0.123878    0.221137
Western Europe                                        0.231463    0.302109

                                 Dystopia Residual
Region
Australia and New Zealand                 2.265355
Central and Eastern Europe                2.021400
Eastern Asia                              1.681607
Latin America and Caribbean               2.622577
Middle East and Northern Africa           1.980008
North America                             2.480935
Southeastern Asia                         1.783020
Southern Asia                             2.016769
Sub-Saharan Africa                        2.019980
Western Europe                            2.151185

                                      sum      mean
Region
Australia and New Zealand         14.570  7.285000
Central and Eastern Europe       154.655  5.332931
Eastern Asia                      33.757  5.626167
Latin America and Caribbean      135.183  6.144682
Middle East and Northern Africa  108.138  5.406900
North America                     14.546  7.273000
Southeastern Asia                 47.857  5.317444
Southern Asia                     32.066  4.580857
Sub-Saharan Africa               168.112  4.202800
Western Europe                   140.482  6.689619

C:\Users\Phillip\AppData\Local\Temp\ipykernel_26380\3196061636.py:17: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  print('\n', Region_Grouping['Happiness Score'].agg([sum, np.mean]))
C:\Users\Phillip\AppData\Local\Temp\ipykernel_26380\3196061636.py:17: FutureWarning: The provided callable <function mean at 0x000001AB1CD06160> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  print('\n', Region_Grouping['Happiness Score'].agg([sum, np.mean]))

In [ ]:
#Can Select the Group to perform Aggegrations on 
Region_Grouping['Economy (GDP per Capita)'].mean()

Region
Australia and New Zealand          1.291880
Central and Eastern Europe         0.942438
Eastern Asia                       1.151780
Latin America and Caribbean        0.876815
Middle East and Northern Africa    1.066974
North America                      1.360400
Southeastern Asia                  0.789054
Southern Asia                      0.560486
Sub-Saharan Africa                 0.380473
Western Europe                     1.298596
Name: Economy (GDP per Capita), dtype: float64

In [54]:
#Can Select the column from the aggregration
Region_Grouping.mean(numeric_only=True)['Economy (GDP per Capita)']

Region
Australia and New Zealand          1.291880
Central and Eastern Europe         0.942438
Eastern Asia                       1.151780
Latin America and Caribbean        0.876815
Middle East and Northern Africa    1.066974
North America                      1.360400
Southeastern Asia                  0.789054
Southern Asia                      0.560486
Sub-Saharan Africa                 0.380473
Western Europe                     1.298596
Name: Economy (GDP per Capita), dtype: float64

In [ ]:
''' 
Agg Method allows multiple aggregrations at once:
    
    GroupBy.agg([function 1, function 2, function 3])



'''

#Don't include () and select numeric columns
print(Region_Grouping['Happiness Score'].agg([sum, np.mean]))

#Can use custom functions 
def dif(group):
    return group.max() - group.min()

#Select only numeric columns to avoid issues
print('\n', Region_Grouping['Happiness Score'].agg([dif]))

                                     sum      mean
Region
Australia and New Zealand         14.570  7.285000
Central and Eastern Europe       154.655  5.332931
Eastern Asia                      33.757  5.626167
Latin America and Caribbean      135.183  6.144682
Middle East and Northern Africa  108.138  5.406900
North America                     14.546  7.273000
Southeastern Asia                 47.857  5.317444
Southern Asia                     32.066  4.580857
Sub-Saharan Africa               168.112  4.202800
Western Europe                   140.482  6.689619

                                    dif
Region
Australia and New Zealand        0.002
Central and Eastern Europe       2.287
Eastern Asia                     1.424
Latin America and Caribbean      2.708
Middle East and Northern Africa  4.272
North America                    0.308
Southeastern Asia                2.979
Southern Asia                    1.678
Sub-Saharan Africa               2.638
Western Europe                   2.730

C:\Users\Phillip\AppData\Local\Temp\ipykernel_26380\3319332388.py:9: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  print(Region_Grouping['Happiness Score'].agg([sum, np.mean]))
C:\Users\Phillip\AppData\Local\Temp\ipykernel_26380\3319332388.py:9: FutureWarning: The provided callable <function mean at 0x000001AB1CD06160> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  print(Region_Grouping['Happiness Score'].agg([sum, np.mean]))

In [ ]:
''' 
Pivot Tables

Arguments in Pivot Table are analogous e.g.,
    groupby([index of col to be selected])['values we want'].func()
                ^ index                     ^values            ^agg func


    '''

$$ Geometric \; Brownian \; Motion $$
We can compact the random generations by centering the distribution at $\mu*dt$ and scaling it by $\sigma \sqrt{dt}$ directly, and also directly cumprod() the dataframe

In [3]:

def geometric_brownian_return_efficient(n_years = 10, scenarios = 1000,
                              drift=0.07, volatility=0.15, 
                              dt_steps_per_year = 12,
                              s_0 = 100, prices = True):
    
    #Steps : number of years * steps per years

    dt = 1/dt_steps_per_year
    number_of_steps = int(n_years * dt_steps_per_year)

#We want to generate matrix of random numbers for the Brownian component
#Number of row is the new stock price, and every column is each scenario

    returns = np.random.normal(loc= (1+ drift )** dt, scale = (volatility * np.sqrt(dt)), 
                          size=(number_of_steps, scenarios))

#Make sure all returns start at s_0 by setting first return to 1 
    returns[0] = 1
    
#Convert returns to prices
    prices = s_0 * pd.DataFrame(returns).cumprod() if prices else returns-1
    return prices

In [18]:
def plot_GBM(scenarios, drift, volatility):
    'Uses GBM Function from this file'
    s_0 = 100
    prices = geometric_brownian_return_efficient(
        scenarios=scenarios, drift=drift, volatility=volatility, s_0=s_0)
    #Plotting the Price Evolution
    ax = prices.plot(legend = False, alpha = 0.5, linewidth =2, figsize=(12,6))
    ax.axhline(y = 100, ls=':', color='black')
    #Set the Y-axis so it doesn't change 
    ax.set_ylim(top = 1000, bottom = -100)
    #Draw the plot with dot at origin
    ax.plot(0,s_0, marker='o',color='darkred', alpha=0.2)

## This creates the panel that you can change parameters for. Pass the function 
## to make interactive as the first argument, and next arguements use a tuple to 
## specify start, end, step

$$ CPPI \; Back-Testing $$

1. Running Backtest of CPPI Strategy (using GBM simulations)
2. Show results of MC CPPI backtest (including histogram of floor violations)
3. Summary Statistics of backtest

In [16]:
def show_cppi(scenarios=50, drift=0.07, volatility=0.15, m=3, floor=0., riskfree_rate=0.03, y_max=100, dt_steps_per_year = 12):
    """
    Plot the results of a Monte Carlo Simulation of CPPI
    """
    #Setting up GBM for risky returns evolution simulation
    start = 100
    sim_rets = geometric_brownian_return_efficient(scenarios=scenarios, drift=drift,
                                                   volatility=volatility, dt_steps_per_year=dt_steps_per_year,
                                                   prices=False)
    risky_r = pd.DataFrame(sim_rets)

    # run the CPPI backtest
    btr = run_cppi(risky_r=pd.DataFrame(risky_r),riskfree_rate=riskfree_rate,m=m, start=start, floor=floor)
    wealth = btr["Wealth"]

    # calculate terminal wealth stats
    terminal_wealth = wealth.iloc[-1]
    tw_mean = terminal_wealth.mean()
    tw_median = terminal_wealth.median()

    'Create a Boolean mask that shows violations of when terminal wealth ends up less than start * floor'
    failure_mask = np.less(terminal_wealth, start*floor)
    number_of_failures = failure_mask.sum() #Sum of boolean variables gives number of failures
    percentage_failures = number_of_failures/scenarios 

    #When there is a failure, what is the average magnitude of the failure (conditional expectation)
    #Tenary expression to make sure if there are no violations we don't print EShortfall
    Expected_Shortfall = np.dot(terminal_wealth-start*floor, failure_mask)/number_of_failures if number_of_failures >0 else 0.0
    
    ' Plotting  '

    #Make sub plots -> sets them into table 1 x 2, shares same y axis, set width ratio to 3:2
    fig, (wealth_ax, hist_ax) = plt.subplots(nrows=1, ncols=2, sharey=True, gridspec_kw={'width_ratios':[3,2]}, figsize=(24, 9))
    
    #Makes subplot next to each other with no white space in between
    plt.subplots_adjust(wspace=0.0)
    
    #Plot wealth evolution 
    wealth.plot(ax=wealth_ax, legend=False, alpha=0.3, color="indianred")
    wealth_ax.axhline(y=start, ls=":", color="black")
    wealth_ax.axhline(y=start*floor, ls="--", color="red")

    #Set Y limit axis
    y_max=wealth.values.max()*y_max/100
    wealth_ax.set_ylim(top=y_max)
    
    #Plotting histogram of terminal values
    terminal_wealth.plot.hist(ax=hist_ax, bins=50, ec='w', fc='indianred', orientation='horizontal')
    hist_ax.axhline(y=start, ls=":", color="black")

    #Display EShortfall summary statistics 
    terminal_wealth.plot.hist(ax=hist_ax, bins=50, ec='w', fc='indianred', orientation='horizontal')
    hist_ax.axhline(y=start, ls=":", color="black")
    hist_ax.axhline(y=tw_mean, ls=":", color="blue")
    hist_ax.axhline(y=tw_median, ls=":", color="purple")

    #Annotating values on plot
    hist_ax.annotate(f"Mean: ${int(tw_mean)}", xy=(.7, .9),xycoords='axes fraction', fontsize=24)
    hist_ax.annotate(f"Median: ${int(tw_median)}", xy=(.7, .85),xycoords='axes fraction', fontsize=24)
    if (floor > 0.01):
        hist_ax.axhline(y=start*floor, ls="--", color="red", linewidth=3)
        hist_ax.annotate(f"Violations: {number_of_failures} ({percentage_failures*100:2.2f}%)\nE(shortfall)=${e_shortfall:2.2f}")

In [15]:
def run_cppi(risky_r, safe_r=None, m=3, start=1000, floor=0.8, riskfree_rate=0.03, drawdown=None):
    """
    Run a backtest of the CPPI strategy, given a set of returns for the risky asset
    Returns a dictionary containing: Asset Value History, Risk Budget History, Risky Weight History
    """
    # set up the CPPI parameters
    dates = risky_r.index
    n_steps = len(dates)
    account_value = start
    floor_value = start*floor
    peak = account_value
    if isinstance(risky_r, pd.Series): 
        risky_r = pd.DataFrame(risky_r, columns=["R"])

    if safe_r is None:
        safe_r = pd.DataFrame().reindex_like(risky_r)
        safe_r.values[:] = riskfree_rate/12 # fast way to set all values to a number
    # set up some DataFrames for saving intermediate values
    account_history = pd.DataFrame().reindex_like(risky_r)
    risky_w_history = pd.DataFrame().reindex_like(risky_r)
    cushion_history = pd.DataFrame().reindex_like(risky_r)
    floorval_history = pd.DataFrame().reindex_like(risky_r)
    peak_history = pd.DataFrame().reindex_like(risky_r)

    for step in range(n_steps):
        if drawdown is not None:
            peak = np.maximum(peak, account_value)
            floor_value = peak*(1-drawdown)
        cushion = (account_value - floor_value)/account_value
        risky_w = m*cushion
        risky_w = np.minimum(risky_w, 1)
        risky_w = np.maximum(risky_w, 0)
        safe_w = 1-risky_w
        risky_alloc = account_value*risky_w
        safe_alloc = account_value*safe_w
        # recompute the new account value at the end of this step
        account_value = risky_alloc*(1+risky_r.iloc[step]) + safe_alloc*(1+safe_r.iloc[step])
        # save the histories for analysis and plotting
        cushion_history.iloc[step] = cushion
        risky_w_history.iloc[step] = risky_w
        account_history.iloc[step] = account_value
        floorval_history.iloc[step] = floor_value
        peak_history.iloc[step] = peak
    risky_wealth = start*(1+risky_r).cumprod()
    backtest_result = {
        "Wealth": account_history,
        "Risky Wealth": risky_wealth, 
        "Risk Budget": cushion_history,
        "Risky Allocation": risky_w_history,
        "m": m,
        "start": start,
        "floor": floor,
        "risky_r":risky_r,
        "safe_r": safe_r,
        "drawdown": drawdown,
        "peak": peak_history,
        "floor": floorval_history
    }
    return backtest_result

$$Interactive \; Plots$$

In [ ]:
''' Interactive Plot of GBM '''
widgets.interactive(plot_GBM,
                    scenarios = (1, 20, 5),
                    drift = (0, 0.2, 0.01),
                    volatility = (0, .15, 0.05)
                    )

In [ ]:
''' Interactive Plot of CPPI Back-test'''
widgets.interactive(show_cppi, 
                                   scenarios=widgets.IntSlider(min=1, max=1000, step=5, value=50), 
                                   mu=(0., +.2, .001),
                                   sigma=(0, .3, .05),
                                   floor=(0, 2, .1),
                                   m=(1, 5, .5),
                                   riskfree_rate=(0, .05, .01),
                                   dt_steps_per_year = widgets.IntSlider(min = 1, max = 12, step = 1, value =12,
                                                                         description ='Rebalancing Periods'),
                                   y_max=widgets.IntSlider(min=0, max=100, step=1, value=100,
                                                          description="Zoom Y Axis")
)

$$ Basic \; Summary \; Statistics $$

Functions include
1. Compound set of returns  
2. Annualising Returns
3. Annualising Volatility
4. Computing Semideviation
5. Skew & Kurtosis
6. Summary Statistics (returns dataframe of stats for a table of time series returns)

In [20]:
def compound(r):
    """
    returns the result of compounding the set of returns in r
    """
    return np.expm1(np.log1p(r).sum())

def annualised_returns(r, periods):
    compounded_growth = (1 + r).prod()
    n = r.shape[0]
    return compounded_growth ** (periods / n) - 1

def annualised_vol(r, periods):
    vol = r.std()
    return vol * (periods**0.5)

def semideviation(strat = pd.Series):
    negative_returns = strat < 0 
    standard_deviation = strat.loc[negative_returns].std()
    return standard_deviation

def skew(strat = pd.Series):
    skewness = scipy.stats.skew(strat)
    return skewness

def kurt(strat = pd.Series):
    kurt = scipy.stats.kurtosis(strat)
    return kurt

In [21]:
'''
Will return a dataframe of aggregrated summary statistics for the returns in the columns of
input dataframe r
'''

def summary_stats(r, riskfree_rate=0.03):
    """
    Return a DataFrame that contains aggregated summary stats for the returns in the columns of r
    """
    ann_r = r.aggregate(annualize_rets, periods_per_year=12)
    ann_vol = r.aggregate(annualize_vol, periods_per_year=12)
    ann_sr = r.aggregate(sharpe_ratio, riskfree_rate=riskfree_rate, periods_per_year=12)
    dd = r.aggregate(lambda r: drawdown(r).Drawdown.min())
    skew = r.aggregate(skewness)
    kurt = r.aggregate(kurtosis)
    cf_var5 = r.aggregate(var_gaussian, modified=True)
    hist_cvar5 = r.aggregate(cvar_historic)
    return pd.DataFrame({
        "Annualized Return": ann_r,
        "Annualized Vol": ann_vol,
        "Skewness": skew,
        "Kurtosis": kurt,
        "Cornish-Fisher VaR (5%)": cf_var5,
        "Historic CVaR (5%)": hist_cvar5,
        "Sharpe Ratio": ann_sr,
        "Max Drawdown": dd
    })

$$ Reading \; in \; Time \; Series$$

In [ ]:
def standardised_time_index(df):
    'Turns it into decimals and converts indexes to monthly periods'
    df = df / 100
    df.index = pd.to_datetime(df.index, format = '%Y%m').to_period('M')
    df.columns = df.columns.str.rstrip()
    return df

def date_time_slice(dataframe, start_date, end_date):
    start = dt.datetime.strptime(start_date, '%Y/%m')
    end = dt.datetime.strptime(end_date, '%Y/%m')
    new_df = dataframe.loc[start:end]
    return new_df

def covariance_matrix(df):
    cov = df.cov()
    return cov

In [3]:
def drawdown(r):
    #Compute wealth over time (cumulative returns)
    wealth_level = 1000 * (1 + r).cumprod()
    peak = wealth_level.cummax()
    drawdown = (wealth_level - peak) / peak

    output = pd.DataFrame(  {'Wealth' : wealth_level,
                            'Peaks' : peak,
                            'Drawdown' : drawdown}
                            )
    return output

In [ ]:
def var(returns, level=5):
    
    if isinstance(returns, pd.DataFrame):
        return returns.apply(lambda col : var(col, level = level))
    
    if isinstance(returns, pd.Series):
        return -np.percentile(returns, level)
    else:
        print('Try again')
    

def gaussian_var(returns, level=1, modified=False):

    z = scipy.stats.norm.ppf(level/100)
    
    if modified:

        s = scipy.stats.skew(returns)
        k = scipy.stats.kurtosis(returns) + 3

        z = (z +
                (z**2 - 1)*s/6 +
                (z**3 -3*z)*(k-3)/24 -
                (2*z**3 - 5*z)*(s**2)/36
            )        
    if isinstance(returns, pd.DataFrame):
        return returns.agg(gaussian_var, level = level)
    
    if isinstance(returns, pd.Series):
        return -(returns.mean() + z * returns.std(ddof=0))

$$ Mean-Variance \; Optimisation $$

Functions include 
1. Optimisation to return lowest volatility for a given return vector
2. Optimisation to return best Sharpe portfolio (tangency portfolio)
3. Optimisation to find 'nose' of MV-frontier 

Check Module-2 EDHEC Assignment to see how to run functions e.g., passing arguments

In [ ]:
def equal_weight(data):
    n = data.shape[1]
    w = np.ones(n) * 1/n * 100
    return w

def minimize_volatility(target_return, returns, covariance):

    #Create initial guess and weight constraint vector 
    n = returns.shape[0]
    initial_guess = np.ones(n) * 1/n
    weight_constraint = ((0.0, 1.0),) * n

    #Construct optimisation constraints
    weight_sum_to_1 = {'type': 'eq',
                       'fun' : lambda weights : np.sum(weights) - 1
                       }
    return_is_target = {'type' : 'eq',
                        'args' : (returns,),                   
                        'fun' : lambda weights, returns: weights.T @ returns - target_return
                        }
    
    weights = minimize(portfolio_vol , initial_guess,
             args = (covariance,), method = 'SLSQP',
             options = {'disp': False},
             constraints=(weight_sum_to_1, return_is_target),
             bounds = weight_constraint
    )

    return weights.x

def minimise_sharpe(returns, covariance, riskfree):

    #Create Initial Guess
    n = returns.shape[0]
    initial_guess = np.ones(n) * 1/n
    bounds = ((0.0,1.0),) * n 

    #Constraints
    weights_sum_to_1 = {'type' : 'eq', 
                        'fun' : lambda weights : np.sum(weights) - 1 
    }
    
    #Define Sharpe Ratio Calculator
    def Sharpe_Ratio(weights, returns, riskfree, covariance):
        port_returns = weights.T @ returns
        port_vol = (weights.T @ covariance @ weights) ** 0.5
        return -(port_returns - riskfree)/port_vol
    
    #Run the Optimiser
    weights = minimize(
                    Sharpe_Ratio, initial_guess, 
                       args = (returns, riskfree, covariance),
                       constraints=(weights_sum_to_1),
                       method ='SLSQP',
                       bounds=bounds
                       )
    return weights.x

def global_minimum_vol(covariance):
    #To find the global minimum volatility portfolio, we essientally
    #run an optimisation to find the maximum sharpe but make all asset's
    #returns the same. The optimiser can't optimise for returns so will focus
    #on lowering volatility which gives the 'nose' of the efficient frontier
    number_of_assets = covariance.shape[0]
    returns = np.repeat(1, number_of_assets)
    return minimise_sharpe(returns, covariance, 0)