# Imports & Data

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## Data Preprocess : Checking the Data

In [3]:
#Import Iris Data
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"

In [15]:
raw_df = pd.read_csv(url, header = None, names = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'Class'])

In [18]:
raw_df.head()

   sepal-length  sepal-width  petal-length  petal-width        Class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [20]:
raw_df.shape

(150, 5)

In [34]:
raw_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal-length  150 non-null    float64
 1   sepal-width   150 non-null    float64
 2   petal-length  150 non-null    float64
 3   petal-width   150 non-null    float64
 4   Class         150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [35]:
raw_df.isnull().any()

sepal-length    False
sepal-width     False
petal-length    False
petal-width     False
Class           False
dtype: bool

## Understanding the Data

In [ ]:
#How many types of flowers there are of each class
Flower_Types = raw_df.groupby('Class').mean()
Flower_Types

                 sepal-length  sepal-width  petal-length  petal-width
Class
Iris-setosa             5.006        3.418         1.464        0.244
Iris-versicolor         5.936        2.770         4.260        1.326
Iris-virginica          6.588        2.974         5.552        2.026

In [66]:
#Average characterestics of each flower type
Characterestics_by_Types = raw_df.groupby('Class').aggregate(['std', 'mean'])
Characterestics_by_Types

                sepal-length        sepal-width        petal-length         \
                         std   mean         std   mean          std   mean
Class
Iris-setosa         0.352490  5.006    0.381024  3.418     0.173511  1.464
Iris-versicolor     0.516171  5.936    0.313798  2.770     0.469911  4.260
Iris-virginica      0.635880  6.588    0.322497  2.974     0.551895  5.552

                petal-width
                        std   mean
Class
Iris-setosa        0.107210  0.244
Iris-versicolor    0.197753  1.326
Iris-virginica     0.274650  2.026

## Set up Data for ML

In [ ]:
#Dependent variable
y = raw_df.iloc[:, -1]
#Independent variables (design matrix)
X = raw_df.iloc[:, :-1]

In [84]:
#Create test and training data sets
from sklearn.model_selection import train_test_split

In [113]:
X_train, X_test, y_train, y_test = train_test_split(
                                            X, y,
                                            test_size=0.2, #30% is testing data, if using integer => actual number in test set
                                            random_state=1 
                                            )

print(X_train.shape, X_test.shape, y_test.shape, y_train.shape)

(120, 4) (30, 4) (30,) (120,)

### Feature Scaling

In [91]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler

In [ ]:
SScaler = StandardScaler()

(105, 4)