In [2]:
import numpy as np
import pandas as pd
import datetime as dt
import matplotlib.pyplot as plt
import seaborn as sns

## Reading in Data etc

https://www.usek.edu.lb/Content/Assets/20240205WorkspaceWAinstrumentCode.pdf

In [2]:
import eikon as ek
ek.set_app_key('9fbc5c01e4e34244bb166389f0515e16d536af6c')

In [239]:
NASDAQ_Names = ['MSFT.O','NVDA.O','AAPL.O','AMZN.O','GOOGL.O', 'META.O', 'TSLA.O', 'AVGO.O', 'BRKb.O', 'WMT.O', 'JPM.O', 'V.O', 'LLY.O', 'MA.O', 'NFLX.O', 'XOM.O', 'ORCL.O', 'COST.O', 'HD.O', 'PG.O', 'JNJ.O', 'BAC.O', 'ABBV.O', 'KO.O', 'UNH.O', 'CRM.O', 'TMUS.O', 'PM.O', 'WFC.O', 'CVX.O']
NYSE_Names = ['BRKb.N', 'WMT.N', 'JPM.N', 'V.N', 'LLY.N', 'MA.N', 'XOM.N', 'ORCL.N', 'HD.N', 'PG.N', 'JNJ.N', 'BAC.N', 'ABBV.N', 'KO.N', 'UNH.N', 'CRM.N', 'PM.N', 'WFC.N', 'CVX.N']

In [240]:
# ────────────────────────────────
# 30-largest U.S. companies
# ────────────────────────────────
US_IV_RICS = {
    "MSFT": "MSFTATMIV.U",   # Microsoft          :contentReference[oaicite:1]{index=1}
    "NVDA": "NVDAATMIV.U",   # Nvidia             :contentReference[oaicite:2]{index=2}
    "AAPL": "AAPLATMIV.U",   # Apple              :contentReference[oaicite:3]{index=3}
    "AMZN": "AMZNATMIV.U",   # Amazon             :contentReference[oaicite:4]{index=4}
    "GOOGL": "GOOGLATMIV.U", # Alphabet-A         :contentReference[oaicite:5]{index=5}
    "META": "METAATMIV.U",   # Meta Platforms
    "TSLA": "TSLAATMIV.U",   # Tesla
    "AVGO": "AVGOATMIV.U",   # Broadcom
    "BRKb": "BRKbATMIV.U",   # Berkshire Hathaway-B :contentReference[oaicite:6]{index=6}
    "WMT": "WMTATMIV.U",     # Walmart
    "JPM": "JPMATMIV.U",     # JPMorgan Chase
    "V":   "VATMIV.U",       # Visa A
    "LLY": "LLYATMIV.U",     # Eli Lilly          :contentReference[oaicite:7]{index=7}
    "MA":  "MAATMIV.U",      # Mastercard A
    "NFLX":"NFLXATMIV.U",    # Netflix
    "XOM": "XOMATMIV.U",     # Exxon Mobil
    "ORCL":"ORCLATMIV.U",    # Oracle
    "COST":"COSTATMIV.U",    # Costco
    "HD":  "HDATMIV.U",      # Home Depot
    "PG":  "PGATMIV.U",      # Procter & Gamble
    "JNJ": "JNJATMIV.U",     # Johnson & Johnson
    "BAC": "BACATMIV.U",     # Bank of America
    "ABBV":"ABBVATMIV.U",    # AbbVie
    "KO":  "KOATMIV.U",      # Coca-Cola
    "UNH": "UNHATMIV.U",     # UnitedHealth
    "CRM": "CRMATMIV.U",     # Salesforce
    "TMUS":"TMUSATMIV.U",    # T-Mobile US
    "PM":  "PMATMIV.U",      # Philip Morris Int’l
    "WFC": "WFCATMIV.U",     # Wells Fargo
    "CVX": "CVXATMIV.U"      # Chevron
}

In [223]:
US_Top30_df_NYSE, e = ek.get_data(
                    US_Top_30_Names_NYSE,
                    fields=['TR.OPENPRICE.Date','TR.High', 'TR.Low', 'TR.Open', 'TR.Close', 'TR.Volume'],
                    parameters={'SDate': '2019-01-01',
                                    'EDate': '2025-05-11',
                                    'Frq':'D'}
)

c:\Users\Phillip\AppData\Local\Programs\Python\Python39\lib\site-packages\eikon\data_grid.py:255: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df = df.apply(pd.to_numeric, errors='ignore')

In [38]:
SP_indices = ['.SPX']
fields = ['TR.Close', 'TR.Close.Date']
SP500, e = ek.get_data(SP_indices, fields = fields, parameters = {'SDate': '2005-01-01',
                                    'EDate': '2025-05-11',
                                    'Frq':'D'})
SP500.head()

c:\Users\Phillip\AppData\Local\Programs\Python\Python39\lib\site-packages\eikon\data_grid.py:255: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df = df.apply(pd.to_numeric, errors='ignore')

  Instrument  Price Close                  Date
0       .SPX      1202.08  2005-01-03T00:00:00Z
1       .SPX      1188.05  2005-01-04T00:00:00Z
2       .SPX      1183.74  2005-01-05T00:00:00Z
3       .SPX      1187.89  2005-01-06T00:00:00Z
4       .SPX      1186.19  2005-01-07T00:00:00Z

In [41]:
SP500.set_index('Date', inplace = True)
SP500.index = pd.to_datetime(SP500.index).to_period('D')
SP500.to_csv('SP500_2005_2025.CSV')

C:\Users\Phillip\AppData\Local\Temp\ipykernel_30116\2433216771.py:2: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  SP500.index = pd.to_datetime(SP500.index).to_period('D')

In [39]:
SP_indices = ['.5SP10', '.5SP25', '.5SP40', '.5SP35', '.5SP55','.5SP60', '.5SP15']

In [ ]:
SP_500_Sector_dfs = {}
for i in SP_indices:
    name = str(i) + '_df'
    df = SP_500_2005_2025.groupby('Instrument').get_group(str(i))
    df.set_index('Date', inplace = True)
    df.index = pd.to_datetime(df.index).to_period('D')
    SP_500_Sector_dfs[name] = df
    df.to_csv(f'SP500_Sector_{name}_2005_2025.csv')

C:\Users\Phillip\AppData\Local\Temp\ipykernel_30116\1105127967.py:7: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  df.index = pd.to_datetime(df.index).to_period('D')
C:\Users\Phillip\AppData\Local\Temp\ipykernel_30116\1105127967.py:7: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  df.index = pd.to_datetime(df.index).to_period('D')
C:\Users\Phillip\AppData\Local\Temp\ipykernel_30116\1105127967.py:7: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  df.index = pd.to_datetime(df.index).to_period('D')
C:\Users\Phillip\AppData\Local\Temp\ipykernel_30116\1105127967.py:7: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  df.index = pd.to_datetime(df.index).to_period('D')
C:\Users\Phillip\AppData\Local\Temp\ipykernel_30116\1105127967.py:7: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  df.index = pd.to_datetime(df.index).to_period('D')
C:\Users\Phillip\AppData\Local\Temp\ipykernel_30116\1105127967.py:7: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  df.index = pd.to_datetime(df.index).to_period('D')
C:\Users\Phillip\AppData\Local\Temp\ipykernel_30116\1105127967.py:7: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  df.index = pd.to_datetime(df.index).to_period('D')

In [36]:
SP_500_Sector_dfs['.5SP35_df']

           Instrument  Close Price
Date
2005-01-03     .5SP35     346.8074
2005-01-04     .5SP35     344.2478
2005-01-05     .5SP35     343.1532
2005-01-06     .5SP35      345.624
2005-01-07     .5SP35     345.7193
...               ...          ...
2025-05-05     .5SP35    1608.2907
2025-05-06     .5SP35    1563.9829
2025-05-07     .5SP35    1576.6565
2025-05-08     .5SP35    1562.2415
2025-05-09     .5SP35    1545.0873

[5310 rows x 2 columns]

In [241]:
US_Top30_ATM_Vols_df ,e = ek.get_data(
                        list(US_IV_RICS.values()),
                        fields = ['TR.30DAYATTHEMONEYIMPLIEDVOLATILITYINDEXFORPUTOPTIONS.Date',
                                'TR.30DAYATTHEMONEYIMPLIEDVOLATILITYINDEXFORPUTOPTIONS'],
                        parameters= {'SDate': '2019-01-01',
                                    'EDate': '2025-05-11',
                                    'Frq':'D'}) 

US_Top30_ATM_Vols_df = US_Top30_ATM_Vols_df.rename(columns={v: k for k, v in IDX_IV_RICS.items()})

c:\Users\Phillip\AppData\Local\Programs\Python\Python39\lib\site-packages\eikon\data_grid.py:255: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df = df.apply(pd.to_numeric, errors='ignore')

In [8]:
big_df = pd.read_csv('SP500_2005_2025.csv', parse_dates = True)
a = pd.read_csv('SkewX_2005_2025.csv', parse_dates = True).dropna()
#b = pd.read_csv(r'C:\Users\Phillip\Desktop\Python\Python Notebooks (Mine)\Dispersion\GARCH MIDAS\GARCH Datasets\RVol_2005_2025.csv', parse_dates=True).dropna()
e = pd.read_csv('VIX_2005_2025.csv', parse_dates = True)
f = pd.read_csv('VVIX_2006_2025.csv', parse_dates = True)

In [95]:
big_df = pd.read_csv('SP500_2005_2025.csv', parse_dates = True)
skew = pd.read_csv('SkewX_2005_2025.csv', parse_dates = True).dropna()
rvol = pd.read_csv('RVol_2005_2025.csv', parse_dates=True).dropna()
vix = pd.read_csv('VIX_2005_2025.csv', parse_dates = True)
vvix = pd.read_csv('VVIX_2006_2025.csv', parse_dates = True)
move = pd.read_csv('MOVE_2005_2025.csv', parse_dates=True)
citi = pd.read_csv('Citi Suprise Economic index 2005-2025.csv', parse_dates=True)
gold = pd.read_csv('GVZ_2008_2025.csv', parse_dates=True)
oil = pd.read_csv('OVX_2007_2025.csv', parse_dates=True)

abc = [big_df, skew, rvol, vix, vvix, move, citi, gold, oil]
df_dict = {}
length = {}
for i in abc:
    df_copy = i.copy()
    df_copy.reset_index(inplace= True)
    df_copy = df_copy.drop_duplicates(subset=['Date']).set_index('Date')
    df_copy.index = pd.to_datetime(df_copy.index)
    df_copy = df_copy.loc['2006-03-01':'2025-05-05']
    name = df_copy['Instrument'].iloc[0].strip('.')
    df_copy.drop(columns = ['Instrument', 'index'], inplace = True)
    df_copy.columns = [name]
    df_dict[name] = df_copy
    length[name] = (df_copy.shape[0])

In [96]:
smallest_ = min(length, key = length.get)

for i in df_dict:
    if i != smallest_:
        df_mask = df_dict[i].index.difference(df_dict[smallest_].index)
        df = df_dict[i].drop(df_mask)
        df_dict[smallest_][i] = df
    else:
        pass

g = df_dict[smallest_].dropna().drop_duplicates(keep='first')


#Attaching GEP and GPR
GPR = pd.read_csv('Geopolitical Risk 1985-2025.csv', parse_dates=True).set_index('month')
GPR.index.name = 'Date'
GPR.index = pd.to_datetime(GPR.index)

GEP = pd.read_csv('Global Economic Policy Uncertainty Data.csv', parse_dates=True, index_col = 'Date')
GEP.columns = ['GEP']

#Assign to Main dataframe of SP
g['GPR'] = GPR['GPR'].reindex(g.index, method = 'ffill')
g['Month'] = g.index.to_period('M').start_time
g['GEP'] = GEP['GEP'].reindex(g.index, method = 'ffill')
#Check
print(g.duplicated(keep=False).isnull().value_counts())

False    4090
Name: count, dtype: int64

In [98]:
g.to_csv('SP_VIX_VVIX_SKEW_GPR_GEP_MOVE_CITI_GOLD_OIL_2008.csv')

In [97]:
g

,GVZ,SPX,SKEWX,RVOL,VIX,VVIX,MOVE,CESIUSD,OVX,GPR,Month,GEP
Date,,,,,,,,,,,,
2008-06-03,22.89,1377.65,114.60,13.50,20.24,79.72,132.70,-4.5,41.75,87.548424,2008-06-01,88.590383
2008-06-04,22.69,1377.20,114.37,13.42,20.80,81.04,131.90,-1.5,40.77,87.548424,2008-06-01,88.590383
2008-06-05,22.78,1404.05,114.76,14.64,18.63,79.35,133.80,-0.9,41.37,87.548424,2008-06-01,88.590383
2008-06-06,23.60,1360.68,113.55,17.02,23.56,88.78,139.60,-5.3,52.03,87.548424,2008-06-01,88.590383
2008-06-09,24.47,1361.76,114.98,16.98,23.12,92.23,151.00,-2.6,45.57,87.548424,2008-06-01,88.590383
...,...,...,...,...,...,...,...,...,...,...,...,...
2025-01-17,14.98,5996.66,165.35,17.18,15.97,101.61,95.60,22.8,33.52,112.377914,2025-01-01,365.025208
2025-01-21,15.50,6049.24,173.00,17.40,15.06,98.26,96.78,20.6,35.10,112.377914,2025-01-01,365.025208
2025-01-22,15.24,6086.37,179.98,13.97,15.10,100.56,89.90,19.8,34.68,112.377914,2025-01-01,365.025208
2025-01-23,14.95,6118.71,179.32,14.11,15.02,99.52,88.51,18.7,34.18,112.377914,2025-01-01,365.025208
2025-01-24,14.85,6101.24,173.16,13.66,14.85,100.41,86.75,10.1,29.98,112.377914,2025-01-01,365.025208

Empty DataFrame
Columns: [MOVE, SPX, SKEWX, RVOL, VIX, VVIX, CESIUSD, GPR, Month, GEP]
Index: []

In [58]:
move_df[move_df.index.duplicated()]

Empty DataFrame
Columns: [Date, Instrument, Close Price]
Index: []

In [26]:
''' g = pd.read_csv(r'C:\Users\Phillip\Desktop\Python\Python Notebooks (Mine)\Dispersion\GARCH MIDAS\GARCH Datasets\SP_VIX_VVIX_SKEW_RV_2006_2025.csv', parse_dates = True, index_col='date')
g.drop_duplicates(inplace = True)
g['Returns'] = np.log(g['SPX'] / g['SPX'].shift(1)) * 100
g.dropna(inplace = True)
g['GPR'] = d['GPR'].reindex(g.index, method = 'ffill')
g['month value'] = g.index.to_period('M').start_time
g.to_csv('SP_VIX_VVIX_SKEW_RV_2006_2025_with_GPR.csv')'''

SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 21-22: truncated \UXXXXXXXX escape (382229471.py, line 7)

In [99]:
g[g.duplicated(keep=False)]

              VVIX      SPX   SKEWX    VIX
Date
2021-09-03  105.48  4535.43  162.27  16.41
2021-09-06  105.48  4535.43  162.27  16.41
2021-11-24  110.48  4701.46  148.15  18.58
2021-11-25  110.48  4701.46  148.15  18.58
2021-12-23  120.46  4725.79  150.26  17.96
2021-12-24  120.46  4725.79  150.26  17.96
2022-01-14  117.57  4662.85  133.85  19.19
2022-01-17  117.57  4662.85  133.85  19.19
2022-02-18  133.64  4348.87  128.36  27.75
2022-02-21  133.64  4348.87  128.36  27.75
2022-04-14  114.75  4392.59  134.39  22.70
2022-04-15  114.75  4392.59  134.39  22.70

In [75]:
mask = df_dict['SPX'].index.difference(df_dict[smallest_].index)
sp_2 = df_dict['SPX'].drop(mask)

In [79]:
sp_2['VVIX'] = df_dict['VVIX'].values

In [32]:
sp_df.index.difference(skew_df.index)

PeriodIndex(['2011-02-09', '2011-08-29', '2011-10-26', '2011-11-14',
             '2014-04-24', '2014-04-30', '2014-05-01', '2018-05-11',
             '2019-11-20', '2020-02-27', '2023-09-26', '2024-11-29'],
            dtype='period[D]', name='Date')

In [464]:
vix_df.index.difference(sp_df.index)

PeriodIndex(['2011-09-05', '2022-11-24', '2022-12-26', '2023-01-02',
             '2023-01-16', '2023-02-20', '2023-05-29', '2023-06-19',
             '2023-07-04', '2023-09-04', '2023-11-23', '2024-01-15',
             '2024-02-19', '2024-05-27', '2024-06-19', '2024-07-04',
             '2024-09-02', '2024-11-28', '2025-01-09', '2025-01-20',
             '2025-02-17'],
            dtype='period[D]', name='Date')

In [472]:
print(vix_df.shape[0])
print(sp_df.shape[0])

4857
4836

In [457]:
g = df_dict['SPX']
g['VIX'] = df_dict['VIX']['VIX'].values
g['VVIX'] = df_dict['VVIX']['VVIX'].values
g['Skew'] = df_dict['SKEWX']['SKEWX'].values
g['Realized Vol'] = df_dict['RVOL']['RVOL'].values
g

ValueError: Length of values (4857) does not match length of index (4836)

In [451]:
g.drop_duplicates().shape

(4784, 1)

In [384]:
c = pd.read_csv(r'C:\Users\Phillip\Desktop\Python\Python Notebooks (Mine)\Dispersion\GARCH MIDAS\GARCH Datasets\Citi Suprise Economic Index 2005-2025.csv', parse_dates = True)
d = pd.read_csv(r'C:\Users\Phillip\Desktop\Python\Python Notebooks (Mine)\Dispersion\GARCH MIDAS\GARCH Datasets\Geopolitical Risk 1985-2025.csv', parse_dates = True)

### To Save

In [ ]:
#Useful for checking what indices are missing
ids = set(CES.index).intersection(set(g.index))
d1 = CES[CES.index.isin(ids)]
d2 = g[g.index.isin(ids)]
CES.index.difference(d1.index)

Index(['2006-04-14', '2006-05-29', '2006-07-04', '2006-09-04', '2006-11-23',
       '2006-12-25', '2007-01-01', '2007-01-02', '2007-01-15', '2007-02-19',
       ...
       '2024-06-19', '2024-07-04', '2024-09-02', '2024-11-28', '2024-12-25',
       '2025-01-01', '2025-01-09', '2025-01-20', '2025-02-17', '2025-04-18'],
      dtype='object', name='Date', length=141)

In [440]:
#Check for Duplicates
VIX_df_mask = VIX_df3.index.duplicated(keep=False)
VIX_df3[VIX_df_mask]

Empty DataFrame
Columns: [Instrument, Price Close]
Index: []

In [ ]:
#Check for Different Entries between 2 Dataframes
VIX_df3.index.difference(g.index)

Index(['Instrument', 'Price Close'], dtype='object')